### ISSUE TITLE
Firebase 함수 정리

### ISSUE THREAD

**Issue by foba1** [harrywinks/IOT_RFID_security_system#3]
코드가 난잡한 느낌이라 필요한 함수만 보기 쉽게 정리하였습니다.

def get_doc(coll_name, doc_name)
coll_name에 해당하는 collection에서 doc_name의 이름을 갖는 document를 검색하고 이를 반환.

dof update_doc(coll_name, doc_name, field_name, value)
coll_name에 해당하는 collection에서 doc_name의 이름을 갖는 document의 특정 필드의 값을 수정.

def delete_document(coll_name, doc_name)
coll_name에 해당하는 collection에서 doc_name의 이름을 갖는 document를 삭제.

def register_material(material_id, _user_id, _due_date, _export_date, _security_level, _salt)
material collection에 정보를 등록.

def register_user(_user_id, _user_name, _password, _entry_time, _exit_time, _salt)
user collection에 정보를 등록.

**Comment by skwent77** [comment]
확인이 늦었습니다. 

일단 필요한 함수는 다 만들어주신 것 같습니다!
